# Generated by Django 4.1.13 on 2024-01-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nombreEmprendimiento',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
