# Generated by Django 4.1.13 on 2024-01-14 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emprendimiento', '0002_emprendimiento_tipoemprendimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precioVentaPorUnidad', models.IntegerField(blank=True, null=True)),
                ('cantidadProyectada', models.IntegerField(blank=True, null=True)),
                ('ingresosAdicionales', models.IntegerField(blank=True, null=True)),
                ('costoPorUnidad', models.IntegerField(blank=True, null=True)),
                ('gastosOperativos', models.IntegerField(blank=True, null=True)),
                ('gastosMarketing', models.IntegerField(blank=True, null=True)),
                ('gastosDesarrollo', models.IntegerField(blank=True, null=True)),
                ('gastosAdicionales', models.IntegerField(blank=True, null=True)),
                ('ingresos', models.IntegerField(blank=True, null=True)),
                ('gastos', models.IntegerField(blank=True, null=True)),
                ('beneficios', models.IntegerField(blank=True, null=True)),
                ('tipoGasto', models.TextField(blank=True, null=True)),
                ('valorGasto', models.IntegerField(blank=True, null=True)),
                ('tipoIngreso', models.TextField(blank=True, null=True)),
                ('valorIngreso', models.IntegerField(blank=True, null=True)),
                ('emprendimiento', models.ManyToManyField(blank=True, to='emprendimiento.emprendimiento')),
                ('usuario', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
