# Generated by Django 4.1.13 on 2024-01-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprendimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprendimiento',
            name='tipoEmprendimiento',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
