# Generated by Django 4.1.13 on 2024-01-14 16:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='temas/')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=400)),
                ('contenido', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('cursos', models.ManyToManyField(blank=True, to='Cursos.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='temas',
            field=models.ManyToManyField(blank=True, to='Cursos.tema'),
        ),
        migrations.CreateModel(
            name='ContenidoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=400)),
                ('pieImagen', models.CharField(max_length=400)),
                ('concepto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ejemplo1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ejemplo2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('ejemplo3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='contenidos/')),
                ('cursos', models.ManyToManyField(blank=True, to='Cursos.curso')),
            ],
        ),
    ]
