# Generated by Django 4.1.13 on 2024-01-14 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='videos/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contenidocurso',
            old_name='cursos',
            new_name='curso',
        ),
        migrations.RemoveField(
            model_name='contenidocurso',
            name='ejemplo1',
        ),
        migrations.RemoveField(
            model_name='contenidocurso',
            name='ejemplo2',
        ),
        migrations.RemoveField(
            model_name='contenidocurso',
            name='ejemplo3',
        ),
        migrations.RemoveField(
            model_name='contenidocurso',
            name='pieImagen',
        ),
        migrations.DeleteModel(
            name='Ejercicio',
        ),
        migrations.AddField(
            model_name='recurso',
            name='ContenidoCurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cursos.contenidocurso'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='contenido_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
