# Generated by Django 4.1.13 on 2024-01-14 18:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_recursoimagen_recursotexto_recursovideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursotexto',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
