# Generated by Django 4.1.13 on 2024-01-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0004_alter_recursotexto_texto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Cursos',
        ),
        migrations.RenameField(
            model_name='contenidocurso',
            old_name='curso',
            new_name='cursos',
        ),
    ]
