# Generated by Django 4.1.13 on 2024-01-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0005_rename_curso_cursos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recursoimagen',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recursotexto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='recursovideo',
            options={},
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='polymorphic_ctype',
        ),
    ]
