# Generated by Django 4.1.13 on 2024-01-14 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Cursos', '0006_alter_recurso_options_alter_recursoimagen_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurso',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='recursoimagen',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='recursotexto',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='recursovideo',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='recurso',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
    ]
